{
   "product":[
      {
         "product":{
            "totalsellers":15,
            "pricemax":"1499.00",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=188924&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=188924&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=188924&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":51,
            "pricemin":"639.20",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":188924,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_188924_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "3"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "18 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=188924&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=188924&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"7.8",
                  "numcomments":39
               }
            },
            "eco":false,
            "productname":"Burigotto Classe 1 BerÃ§o"
         }
      },
      {
         "product":{
            "totalsellers":13,
            "pricemax":"752.54",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=188866&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=188866&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=188866&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":38,
            "pricemin":"447.12",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":188866,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_188866_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "3"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "18 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=188866&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=188866&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"7.8",
                  "numcomments":59
               }
            },
            "eco":false,
            "productname":"Burigotto AT2 BerÃ§o"
         }
      },
      {
         "product":{
            "totalsellers":13,
            "pricemax":"617.40",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=417445&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=417445&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=417445&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":41,
            "pricemin":"359.10",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":417445,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_417445_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "3"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "NÃ£o"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "15 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=417445&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=417445&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"5.2",
                  "numcomments":3
               }
            },
            "eco":false,
            "productname":"Burigotto Rio ReversÃ­vel BerÃ§o"
         }
      },
      {
         "product":{
            "totalsellers":12,
            "pricemax":"1690.00",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=298867&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=298867&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=298867&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":30,
            "pricemin":"448.09",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":298867,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_298867_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "3"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "30 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=298867&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=298867&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"6.8",
                  "numcomments":11
               }
            },
            "eco":false,
            "productname":"Cosco Travel System Reverse CD200TS BerÃ§o"
         }
      },
      {
         "product":{
            "totalsellers":12,
            "pricemax":"817.98",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=303145&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=303145&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=303145&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":37,
            "pricemin":"499.00",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":303145,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_303145_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "15 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=303145&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=303145&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"8.0",
                  "numcomments":8
               }
            },
            "eco":false,
            "productname":"Burigotto AT6 BerÃ§o"
         }
      },
      {
         "product":{
            "totalsellers":10,
            "pricemax":"499.00",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=188908&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=188908&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=188908&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":24,
            "pricemin":"449.10",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":188908,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_188908_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "4"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "NÃ£o"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "18 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=188908&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=188908&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"7.8",
                  "numcomments":23
               }
            },
            "eco":false,
            "productname":"Burigotto X-Treme Simples"
         }
      },
      {
         "product":{
            "totalsellers":10,
            "pricemax":"854.90",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=189621&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=189621&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=189621&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":22,
            "pricemin":"683.90",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":189621,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_189621_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "3"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "18 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=189621&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=189621&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"8.2",
                  "numcomments":22
               }
            },
            "eco":false,
            "productname":"Burigotto Linea BerÃ§o"
         }
      },
      {
         "product":{
            "totalsellers":10,
            "pricemax":"363.90",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=348078&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=348078&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=348078&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":22,
            "pricemin":"161.10",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":348078,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_348078_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "3"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "NÃ£o"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "18 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=348078&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=348078&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"6.0",
                  "numcomments":11
               }
            },
            "eco":false,
            "productname":"Voyage Funny BerÃ§o"
         }
      },
      {
         "product":{
            "totalsellers":10,
            "pricemax":"897.98",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=188912&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=188912&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=188912&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":23,
            "pricemin":"539.08",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":188912,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_188912_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "3"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "18 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=188912&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=188912&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"7.8",
                  "numcomments":10
               }
            },
            "eco":false,
            "productname":"Burigotto Euro6 BerÃ§o"
         }
      },
      {
         "product":{
            "totalsellers":10,
            "pricemax":"1399.00",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=240299&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=240299&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=240299&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":48,
            "pricemin":"961.90",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":240299,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_240299_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "NÃ£o"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "15 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=240299&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=240299&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"8.0",
                  "numcomments":5
               }
            },
            "eco":false,
            "productname":"BebÃª Confort Loola Up Simples"
         }
      },
      {
         "product":{
            "totalsellers":9,
            "pricemax":"329.00",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=188921&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=188921&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=188921&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":15,
            "pricemin":"296.10",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":188921,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_188921_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "3"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "NÃ£o"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "3"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "18 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=188921&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=188921&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"8.0",
                  "numcomments":18
               }
            },
            "eco":false,
            "productname":"Burigotto Bye Bye Simples"
         }
      },
      {
         "product":{
            "totalsellers":9,
            "pricemax":"599.00",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=291641&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=291641&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=291641&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":14,
            "pricemin":"476.91",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":291641,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_291641_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=291641&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=291641&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"9.4",
                  "numcomments":6
               }
            },
            "eco":false,
            "productname":"Burigotto Go Twin GÃªmeos Simples"
         }
      },
      {
         "product":{
            "totalsellers":9,
            "pricemax":"379.00",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=355200&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=355200&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=355200&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":46,
            "pricemin":"274.45",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":355200,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_355200_1.jpg"
            },
            "specification":{
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=355200&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=355200&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"7.4",
                  "numcomments":2
               }
            },
            "eco":false,
            "productname":"Ayoba Supreme PCO-06 BerÃ§o"
         }
      },
      {
         "product":{
            "totalsellers":9,
            "pricemax":"1599.00",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=309264&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=309264&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=309264&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":16,
            "pricemin":"1161.90",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":309264,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_309264_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "3"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "NÃ£o"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=309264&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=309264&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"8.0",
                  "numcomments":1
               }
            },
            "eco":false,
            "productname":"BebÃª Confort Elea Simples"
         }
      },
      {
         "product":{
            "totalsellers":9,
            "pricemax":"1408.00",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=244785&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=244785&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=244785&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":27,
            "pricemin":"899.10",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":244785,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_244785_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "4"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "18 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=244785&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=244785&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"0.0",
                  "numcomments":0
               }
            },
            "eco":false,
            "productname":"Graco Trekko TrÃªs Rodas"
         }
      },
      {
         "product":{
            "totalsellers":8,
            "pricemax":"569.90",
            "fulldescription":false,
            "hasmetasearch":false,
            "links":[
               {
                  "link":{
                     "type":"product",
                     "url":"http://compare.buscape.com.br/prod_unico?idu=188827&mdsrc=9262544&mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"specification",
                     "url":"http://compare.buscape.com.br/prod_ficha?idu=188827&mdsrc=9262544"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?productId=188827&sourceId=9262544&format=json"
                  }
               }
            ],
            "numoffers":26,
            "pricemin":"386.91",
            "currency":{
               "abbreviation":"BRL"
            },
            "id":188827,
            "categoryid":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/thumbs/ensopado/5817/200x200_188827_1.jpg"
            },
            "specification":{
               "item":[
                  {
                     "item":{
                        "value":[
                           "4"
                        ],
                        "label":"Assento ReclinÃ¡vel"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "Sim"
                        ],
                        "label":"Porta Objetos"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "NÃ£o"
                        ],
                        "label":"Bandeja Frontal"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "5"
                        ],
                        "label":"Pontos do Cinto de SeguranÃ§a"
                     }
                  },
                  {
                     "item":{
                        "value":[
                           "17 Kg"
                        ],
                        "label":"Peso Limite"
                     }
                  }
               ],
               "links":[
                  {
                     "link":{
                        "type":"xml",
                        "url":"http://sandbox.buscape.com/service/viewProductDetails/7838643852314c587376343d/br/?productId=188827&sourceId=9262544&format=json"
                     }
                  }
               ]
            },
            "quantity":0,
            "rating":{
               "useraveragerating":{
                  "links":[
                     {
                        "link":{
                           "type":"xml",
                           "url":"http://sandbox.buscape.com/service/viewUserRatings/7838643852314c587376343d/br/?productId=188827&sourceId=9262544&format=json"
                        }
                     }
                  ],
                  "rating":"7.4",
                  "numcomments":35
               }
            },
            "eco":false,
            "productname":"Galzerano Maranello 1380 BerÃ§o"
         }
      }
   ],
   "category":{
      "id":5817,
      "thumbnail":{
         "url":"http://imagem.buscape.com.br/bp5/categorias/5817.jpg"
      },
      "concatenatecategoryname":false,
      "hasoffer":false,
      "name":"Carrinho para BebÃª",
      "parentcategoryid":3473,
      "links":[
         {
            "link":{
               "type":"category",
               "url":"http://compare.buscape.com.br/carrinho-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
            }
         },
         {
            "link":{
               "type":"xml",
               "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5817&sourceId=9262544&format=json"
            }
         }
      ],
      "isfinal":true
   },
   "details":{
      "message":"success",
      "elapsedtime":29,
      "status":"success",
      "code":0,
      "date":{
         "minute":18,
         "valid":true,
         "timezone":-180,
         "second":28,
         "millisecond":318,
         "month":6,
         "year":2013,
         "hour":21,
         "day":9,
         "xmlschematype":{
            "namespaceuri":"http://www.w3.org/2001/XMLSchema",
            "prefix":"",
            "localpart":"dateTime"
         },
         "eonandyear":{
            "lowestsetbit":0
         }
      },
      "applicationid":"7838643852314c587376343d"
   },
   "schk":true,
   "page":1,
   "totallooseoffers":0,
   "totalresultsavailable":373,
   "totalpages":24,
   "match":"all",
   "totalresultsreturned":16
}