{
   "category":{
      "id":3473,
      "thumbnail":{
         "url":"http://imagem.buscape.com.br/bp5/categorias/3473.jpg"
      },
      "concatenatecategoryname":false,
      "hasoffer":true,
      "name":"BebÃªs e Cia",
      "parentcategoryid":0,
      "links":[
         {
            "link":{
               "type":"category",
               "url":"http://compare.buscape.com.br/bebes-e-cia.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
            }
         },
         {
            "link":{
               "type":"xml",
               "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=3473&sourceId=9262544&format=json"
            }
         }
      ],
      "isfinal":false
   },
   "details":{
      "message":"success",
      "elapsedtime":9,
      "status":"success",
      "code":0,
      "date":{
         "minute":33,
         "valid":true,
         "timezone":-180,
         "second":35,
         "millisecond":434,
         "month":6,
         "year":2013,
         "hour":22,
         "day":8,
         "xmlschematype":{
            "namespaceuri":"http://www.w3.org/2001/XMLSchema",
            "prefix":"",
            "localpart":"dateTime"
         },
         "eonandyear":{
            "lowestsetbit":0
         }
      },
      "applicationid":"7838643852314c587376343d"
   },
   "schk":true,
   "subcategory":[
      {
         "subcategory":{
            "id":5805,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5805.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Andador para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/andador-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5805&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":5811,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5811.jpg"
            },
            "concatenatecategoryname":false,
            "name":"Artigos de SeguranÃ§a para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/artigos-de-seguranca-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               }
            ],
            "isfinal":false
         }
      },
      {
         "subcategory":{
            "id":5807,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5807.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"BabÃ¡ EletrÃ´nica",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/baba-eletronica.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5807&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":5812,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5812.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Banheira para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/banheira-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5812&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":11013,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/11013.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"Base de Cadeira para Auto",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/base-de-cadeira-para-auto.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=11013&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":5809,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5809.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"BerÃ§o",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/berco.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5809&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":6536,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/6536.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"Bolsa / Mala / Trocador para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/bolsa-mala-trocador-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=6536&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":2412,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/2412.jpg"
            },
            "concatenatecategoryname":false,
            "name":"Brinquedos para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/brinquedos-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               }
            ],
            "isfinal":false
         }
      },
      {
         "subcategory":{
            "id":10969,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/10969.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"Cadeira de Descanso para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/cadeira-de-descanso-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=10969&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":5816,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5816.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Cadeira para Auto",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/cadeira-para-auto.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5816&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":6557,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/6557.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"Cama / Mesa / Banho para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/cama-mesa-banho-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=6557&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5817.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Carrinho para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/carrinho-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5817&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":9907,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/9907.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Cercado para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/cercado-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=9907&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":3305,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/3305.jpg"
            },
            "concatenatecategoryname":false,
            "name":"Chupeta e AcessÃ³rios",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/chupeta-e-acessorios.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               }
            ],
            "isfinal":false
         }
      },
      {
         "subcategory":{
            "id":8766,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/8766.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"Enfeite / DecoraÃ§Ã£o para Quarto do BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/enfeite-decoracao-para-quarto-do-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=8766&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":482,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/482.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Fralda para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/fralda-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=482&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "subcategory":{
            "id":293,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/293.jpg"
            },
            "concatenatecategoryname":false,
            "name":"Higiene / SaÃºde para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/higiene-saude-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               }
            ],
            "isfinal":false
         }
      },
      {
         "subcategory":{
            "id":3326,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/3326.jpg"
            },
            "concatenatecategoryname":false,
            "name":"Mamadeira e AcessÃ³rios",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/mamadeira-e-acessorios.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               }
            ],
            "isfinal":false
         }
      },
      {
         "subcategory":{
            "id":2470,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/2470.jpg"
            },
            "concatenatecategoryname":false,
            "name":"Moda para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/moda-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               }
            ],
            "isfinal":false
         }
      },
      {
         "subcategory":{
            "id":6160,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/6160.jpg"
            },
            "concatenatecategoryname":false,
            "name":"UtensÃ­lios Diversos para a MamÃ£e",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/utensilios-diversos-para-a-mamae.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               }
            ],
            "isfinal":false
         }
      },
      {
         "subcategory":{
            "id":5865,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5865.jpg"
            },
            "concatenatecategoryname":false,
            "name":"UtensÃ­lios para AlimentaÃ§Ã£o do BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/utensilios-para-alimentacao-do-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               }
            ],
            "isfinal":false
         }
      }
   ],
   "totallooseoffers":0,
   "totalresultsavailable":21,
   "top5category":[
      {
         "top5category":{
            "id":5816,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5816.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Cadeira para Auto",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/cadeira-para-auto.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5816&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":5817,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5817.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Carrinho para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/carrinho-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5817&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":5809,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5809.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"BerÃ§o",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/berco.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5809&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":482,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/482.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Fralda para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/fralda-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=482&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":6554,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/6554.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"CalÃ§ados para BebÃª",
            "parentcategoryid":2857,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/calcados-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=6554&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":6557,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/6557.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"Cama / Mesa / Banho para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/cama-mesa-banho-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=6557&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":5807,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5807.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"BabÃ¡ EletrÃ´nica",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/baba-eletronica.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5807&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":5812,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5812.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Banheira para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/banheira-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5812&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":10730,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/10730.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"CadeirÃ£o para BebÃª",
            "parentcategoryid":5865,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/cadeirao-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=10730&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":10969,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/10969.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"Cadeira de Descanso para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/cadeira-de-descanso-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=10969&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":6536,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/6536.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"Bolsa / Mala / Trocador para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/bolsa-mala-trocador-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=6536&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":3113,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/3113.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"TermÃ´metro",
            "parentcategoryid":2949,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/termometro.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=3113&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":5805,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/5805.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Andador para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/andador-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=5805&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":9907,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/9907.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Cercado para BebÃª",
            "parentcategoryid":3473,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/cercado-para-bebe.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=9907&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":3448,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/3448.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":true,
            "name":"Ãlbum de Fotos",
            "parentcategoryid":2732,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/album-de-fotos.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findOfferList/7838643852314c587376343d/br/?categoryId=3448&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      },
      {
         "top5category":{
            "id":9795,
            "thumbnail":{
               "url":"http://imagem.buscape.com.br/bp5/categorias/9795.jpg"
            },
            "concatenatecategoryname":false,
            "hasoffer":false,
            "name":"Tapetes de Atividades",
            "parentcategoryid":179,
            "links":[
               {
                  "link":{
                     "type":"category",
                     "url":"http://compare.buscape.com.br/tapetes-de-atividades.html?mdsrc=9262544&mdapp=5299&mddtn=51922611"
                  }
               },
               {
                  "link":{
                     "type":"xml",
                     "url":"http://sandbox.buscape.com/service/findProductList/7838643852314c587376343d/br/?categoryId=9795&sourceId=9262544&format=json"
                  }
               }
            ],
            "isfinal":true
         }
      }
   ],
   "totalresultsreturned":21
}